### ISSUE TITLE
SIGRTMIN not toggling

### ISSUE THREAD

**Issue by Kojuma04** [jjsullivan5196/wvkbd#44]
Instead of Toggling it's hidden state it just closes the application.

EDIT: I am on NixOS and use zsh, but I noticed that zsh uses it's own kill command, so I used `/usr/bin/env kill` to use the normal kill command.

**Comment by proycon** [comment]
I tried to reproduce this on the latest version and experience different behaviour, but definitely bugged:

For me the toggling does work, but the keyboard doesn't properly draw again, I
only get a black-filled area. This definitely requires some further
investigation.

**Comment by Darc-Charlie** [comment]
I am experiencing the same issue; the symptoms are exactly what @proycon described.

My workaround for this right now is to send the toggle signal to show the keyboard and then rotate my display using [rot8](https://github.com/efernau/rot8). I may be wrong, but I believe works because screen rotation causes the entire screen to be re-drawn.
