### ISSUE TITLE
Theme gets messed up if the keyboard is opened and closed many times

### ISSUE THREAD

**Issue by rdbo** [jjsullivan5196/wvkbd#59]
wvkbd version: wvkbd-0.14.3
Compositor: river 0.2.6

After opening and closing the keyboard a couple of times, the theme gets messed up.
It is supposed to look like this at all times:
![image](https://github.com/jjsullivan5196/wvkbd/assets/57117082/46502e80-5bc2-49be-a72b-56ccce7c2b7e)

Instead, it will look like this after opening and closing (pkill -9) a couple of times:
![image](https://github.com/jjsullivan5196/wvkbd/assets/57117082/7926519b-abd3-4094-bebf-fc14150fb5db)

I'm not sure what exactly this couple be, but it is very odd.
The command I am using to toggle the keyboard is:
```sh
if pidof wvkbd-mobintl; then
	pkill -9 wvkbd-mobintl
else
	wvkbd-mobintl -L 280 --fn "FiraCode Nerd Font Mono:style=Bold" --bg "1b1b1b" --text "e6e6b5" --text-sp "e6e6b5"
fi
```

**Comment by proycon** [comment]
That is odd behaviour indeed, I have never seen this on any other compositor (Hyprland, sway, wayfire). I also tried river now (0.2.6) with latest git wvkbd and there too I can't reproduce it. A wild guess is that perhaps the latest patches that fixed redrawing fixes this too.

**Comment by rdbo** [comment]
I managed to record a video of me doing this in QEMU with river built on master branch, with wvkbd on v0.14.4
It is kind of annoying to reproduce, but happens once in a while

https://www.youtube.com/watch?v=n_8VfVSNlic&t=65s

**Comment by proycon** [comment]
Spooky, especially that is sometimes reproduces and sometimes not.
I have never experienced this behaviour yet, but I also never tried
River. I would be more inclined to suspect a bug in River (since I
havent't seen it on either sway, Hyprland or Wayfire), but I'm just
guessing here.

Let's keep this open and see if anybody else experiences the same issue
(either on River or another compositor).
