### ISSUE TITLE
Unable to long press for repeated input

### ISSUE THREAD

**Issue by notorangee** [jjsullivan5196/wvkbd#79]
Hello, I'm not sure if I broke something, I can't long press and enter any key repeatedly after installation, wvkbd only outputs one character after I try to long press. I use it on surface go2 and surface pro6 , the same fault, the strange thing is that when I connect the mouse, I can long press and repeat key input, thanks for any help 🙏

**Comment by notorangee** [comment]
> 你好，不知道是不是我弄坏了什么东西，安装后无法长按重复输入任意键，wvkbd 在我尝试长按后只输出一个字符。我在 Surface Go2 和 Surface Pro6 上使用它，同样的故障，奇怪的是当我连接鼠标时，我可以长按并重复输入按键，谢谢任何帮助🙏

After connecting the mouse and using the mouse for long press, it works everything fine but I can't get key repeat input with screen long press

**Comment by notorangee** [comment]
> Hello, I'm not sure if I broke something, I can't long press and enter any key repeatedly after installation, wvkbd only outputs one character after I try to long press. I use it on surface go2 and surface pro6 , the same fault, the strange thing is that when I connect the mouse, I can long press and repeat key input, thanks for any help 🙏

After connecting the mouse and using the mouse for long press, it works everything fine but I can't get key repeat input with screen long press. I use archlinux and use it in hyprland

**Comment by notorangee** [comment]
Note that as long as the contact range of your finger and the screen is small enough and you do not press, you only need to have one point of contact with the screen and do not move, you can get intermittent repeated input, but as long as the contact range is too large, the repeated key input will stop immediately. what happened? Is this related to iptsd's multi-touch?

**Comment by notorangee** [comment]
Note that as long as the contact range of your finger and the screen is small enough and you do not press, you only need to have one point of contact with the screen and do not move, you can get intermittent repeated input, but as long as the contact range is too large, the repeated key input will stop immediately. what happened? Is this related to iptsd multi-touch?

**Comment by notorangee** [comment]
I found out why you can't long press to repeat input. For those who come later, you just need to change the  configuration option #PositionThresholdMin [https://github.com/linux-surface/iptsd/blob/78bfa6958ba25831cb5b47e6ee32f2cf6a460afd/etc/iptsd.conf#L86](url) in IPTSD to a larger parameter, so that IPTSD will not think you are moving your finger and interrupt the long press and repeat input of wvkbd. For reference, I set it to 0.4 and it worked perfectly.

**Comment by petm5** [comment]
I think this needs to be reopened, since setting PositionThresholdMin to a high number in iptsd (in turn drastically lowering the touchscreen precision) seems to be a very hacky workaround, not to mention this setting possibly not existing on other touchscreen drivers. This seems like a problem in wvkbd itself. Maybe wvkbd needs something like a deadzone to detect movement on touchscreens. Other keyboards like squeekboard seem to register a key press as long as the touch point is above the key, but idk if that would interfere with swipe typing.

**Comment by proycon** [comment]
> I think this needs to be reopened, since setting PositionThresholdMin
> to a high number in iptsd (in turn drastically lowering the
> touchscreen precision) seems to be a very hacky workaround, not to
> mention this setting possibly not existing on other touchscreen
> drivers. This seems like a problem in wvkbd itself. Maybe wvkbd needs
> something like a deadzone to detect movement on touchscreens. Other
> keyboards like squeekboard seem to register a key press as long as the
> touch point is above the key, but idk if that would interfere with
> swipe typing.

A deadzone sounds like an acceptable solution if this is indeed a
problem that often occurs. I reopened this issue.

**Comment by icejix** [comment]
@proycon 
It is, indeed. In fact, I'd say that a deadzone is very necessary. Often when I attempt to use key repeat, and move my finger even a small amount on the key, it causes it to be unpressed, decreasing reliability. I may (hackily) edit the source code of my copy in order to fix this, if it is not patched by any contributors of this project.
