### ISSUE TITLE
Where are modified key actions defined?

### ISSUE THREAD

**Issue by RoninTech** [jjsullivan5196/wvkbd#84]
Hi,

I'd like to make it so that when I hit `<shift><up>` it performs a page up and similar for `<shift><down>`.  I see where I can define the displayed string that is drawn for a key when shift is pressed but I don't see where I would tell it to map PgUp and PgDown to shifted up and down?

For example:

`{"↑", "⇈", 0.6, Code, KEY_UP, .scheme = 1},`

So when I hit `<shift><↑>`, the string correctly changes to ⇈ but when I press it, it still just does an up action ↑.

Thanks.

**Comment by proycon** [comment]
Ah sorry, I had overlooked this issue. Modifiers are really just
modifiers in the current implementation, so it means a modifier key is
being held alongside the main key. Two keycodes are sent to the
wayland compositor. It is the job of the active keymap (which wvkbd sets a well) to translate that to a
symbol. So if you want to adapt this behaviour, you have to change the
keymap itself so that SHIFT + UP translates to PageUp.

Look at line 1333 in `keymap_mobintl.h`:

```
key <UP>                 {	[              Up ] };\
```

Adding a second symbol to that array will correspond to the SHIFT
modifier, so I think this should do what you want (untested though):

```
key <UP>                 {	[              Up, Prior ] };\
```

This does mean that all combinations of SHIFT + UP will produce a PageUp (Prior).

**Comment by RoninTech** [comment]
Thanks for the info @proycon, much appreciated.  I made the change to keymap.desktop.h:

`1333 ~ │         key <UP>                 {  [              Up, Prior ] };\`
`1334   │         key <PGUP>               {  [           Prior ] };\`
`1335   │         key <LEFT>               {  [            Left ] };\`
`1336   │         key <RGHT>               {  [           Right ] };\`
`1337   │         key <END>                {  [             End ] };\`
`1338 ~ │         key <DOWN>               {  [            Down, Next ] };\`

And it worked as you described, first time. 👍

**Comment by RoninTech** [comment]
Forgot to ask, what is the third entry in this keymap array for?  For example, the number keys show these shifted values as well as a third value.  How does the third value (F1 - F10) get activated?

`1180   │         key <AE01>               {  [               1,          exclam, F1 ] };\`
`1181   │         key <AE02>               {  [               2,              at, F2 ] };\`
`1182   │         key <AE03>               {  [               3,      numbersign, F3 ] };\`
`1183   │         key <AE04>               {  [               4,          dollar, F4 ] };\`
`1184   │         key <AE05>               {  [               5,         percent, F5 ] };\`
`1185   │         key <AE06>               {  [               6,     asciicircum, F6 ] };\`
`1186   │         key <AE07>               {  [               7,       ampersand, F7 ] };\`
`1187   │         key <AE08>               {  [               8,        asterisk, F8 ] };\`
`1188   │         key <AE09>               {  [               9,       parenleft, F9 ] };\`
`1189   │         key <AE10>               {  [               0,      parenright, F10 ] };\`
`

**Comment by proycon** [comment]
> Forgot to ask, what is the third entry in this keymap array for? 

Typically by AltGr, and then the fourth value would correspond to AltGt+Shift .
